### ISSUE TITLE
Null and blank true won't work

### ISSUE THREAD

**Issue by mgrsantox** [dxillar/django-nepali-datetime-field#3]
My model looks below.
```
from nepali_datetime_field.models import NepaliDateField

created = NepaliDateField(null=True, blank=True)
```
while I run the migration it gives me the error
`AttributeError: 'NoneType' object has no attribute 'to_datetime_date'`

**Comment by amitgaru** [comment]
@mgrsantox Thanks for the report. Do you want to fix it yourself ?

**Comment by sundaradh** [comment]
still not fixed so I fixed it and pull the request

**Comment by amitgaru** [comment]
@sundaradh I have a pending PR. Let me go through your PR as well.
